language: r
cache: packages
sudo: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.1
      brew_packages: poppler
      latex: false

r:
  - bioc-devel
  - bioc-release

bioc_packages:
  - GO.db
  - RamiGO
  - AnnotationDbi
  - Rgraphviz

r_packages:
  - DBI
  - covr
  
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: lg390@cam.ac.uk
    on_failure: lg390@cam.ac.uk

